"""Two-dimensional rigid-grain contact for the GrindCAE 3.0.0 route."""

from .geometry import (
    CircularContactKinematics,
    ContactGeometryError,
    RigidCircularArcGrain,
    RigidCircularGrain,
    RigidContactQuery,
    RigidRoundedWedgeGrain,
    WedgeEffectiveAngles,
    circular_arc_contact_kinematics,
    circular_contact_kinematics,
    rigid_contact_kinematics,
    rigid_contact_query,
    effective_wedge_angles,
    ordered_boundary_tributary_lengths,
)
from .contact_law import (
    ContactPointState,
    FrictionContactResponse,
    NormalContactResponse,
    friction_contact_response,
    normal_contact_response,
    update_augmented_normal_multiplier,
)
from .solver import (
    CommittedContactStructureState,
    ContactConvergenceError,
    ContactSolverError,
    ConvergedContactIncrement,
    PreparedContactMesh,
    advance_normal_contact_increment,
    advance_augmented_contact_increment,
    initial_contact_structure_state,
    prepare_contact_mesh,
    contact_residual_and_tangent,
)
from .models import (
    MODEL_TYPE,
    SCHEMA_VERSION,
    UNIT_SYSTEM,
    SingleGrainContactCase,
    SingleGrainContactValidationError,
)
from .material_topology import (
    MaterialState,
    MaterialTopologyError,
    OrderedFreeSurface,
    PreparedMaterialTopology,
    prepare_material_topology,
)
from .workflow import (
    ContactTrajectoryRecord,
    ContactTrajectoryResult,
    run_contact_trajectory_on_mesh,
)
from .exporters import RESULT_FORMAT
from .exporters_v2 import RESULT_FORMAT_V2
from .api import run_single_grain_contact

__all__ = [
    "CircularContactKinematics",
    "ContactGeometryError",
    "RigidCircularArcGrain",
    "RigidCircularGrain",
    "RigidContactQuery",
    "RigidRoundedWedgeGrain",
    "WedgeEffectiveAngles",
    "circular_arc_contact_kinematics",
    "circular_contact_kinematics",
    "rigid_contact_kinematics",
    "rigid_contact_query",
    "effective_wedge_angles",
    "ordered_boundary_tributary_lengths",
    "ContactPointState",
    "FrictionContactResponse",
    "NormalContactResponse",
    "friction_contact_response",
    "normal_contact_response",
    "update_augmented_normal_multiplier",
    "CommittedContactStructureState",
    "ContactConvergenceError",
    "ContactSolverError",
    "ConvergedContactIncrement",
    "PreparedContactMesh",
    "advance_normal_contact_increment",
    "advance_augmented_contact_increment",
    "initial_contact_structure_state",
    "prepare_contact_mesh",
    "contact_residual_and_tangent",
    "MODEL_TYPE",
    "SCHEMA_VERSION",
    "UNIT_SYSTEM",
    "SingleGrainContactCase",
    "SingleGrainContactValidationError",
    "MaterialState",
    "MaterialTopologyError",
    "OrderedFreeSurface",
    "PreparedMaterialTopology",
    "prepare_material_topology",
    "ContactTrajectoryRecord",
    "ContactTrajectoryResult",
    "run_contact_trajectory_on_mesh",
    "RESULT_FORMAT",
    "RESULT_FORMAT_V2",
    "run_single_grain_contact",
]
